const INCREAMENT = 'INCREAMENT';
const DECREAMENT = 'DECREAMENT';
const RESET = 'RESET';
const INCREAMENT_BY = 'INCREAMENT_BY';
const FETCHING = 'FETCHING';
const FETCH_SUCCESS = 'FETCH_SUCCESS';
const FETCH_ERROR = 'FETCH_ERROR';

export {
	INCREAMENT,
	DECREAMENT,
	INCREAMENT_BY,
	RESET,
	FETCHING,
	FETCH_SUCCESS,
	FETCH_ERROR
};

export enum ActionType {
	fetchToDos
}
